### ISSUE TITLE
Add a Toggleable Setting for only Mob Hearts to be shown or Only Player Hearts

### ISSUE THREAD

**Issue by masterwyatt** [vi945786/MobHealthIndicators#1]
This is more of a suggestion rather than an issue. But I thought this would be helpful if people like me want to have only player hearts visible or mob hearts.

**Comment by JelloBearTV** [comment]
i think this would be perfect!

**Comment by vi945786** [comment]
https://modrinth.com/mod/mobhealthindicators/version/1.2.0
i added a white list and a black list hope that helps
