### ISSUE TITLE
REQUEST: Add a sort of variable view option

### ISSUE THREAD

**Issue by xXEggMannXx** [vi945786/MobHealthIndicators#10]
I propose adding an option to only show health bars when a mob or player has taken damage.  That or a hot key option to toggle the health bars on, off, or hold to display?

**Comment by vi945786** [comment]
there is already a toggle key

**Comment by vi945786** [comment]
I'll try to add the other stuff soon

**Comment by xXEggMannXx** [comment]
I did not realize there is another menu for the toggle key, there have been some changes since the last time I played. I am thankful for the offer to look into the rest, and I appreciate your hard work.
