### ISSUE TITLE
Healthbars sometimes display 0/X hearts above an alive mob

### ISSUE THREAD

**Issue by dotGrim** [vi945786/MobHealthIndicators#4]
Sometimes the healthbars above players or mobs will display 0 hearts, even though the entity's alive. I've seen this happen a lot over the past few weeks, but I'm still not sure why it happens.

Awhile ago when I first started seeing it happen it would toggle between showing actual health and displaying 0/X hearts every time they took damage, but now I don't even know what's toggling it since I haven't been able to recreate it.

![2024-06-07_17 03 45](https://github.com/vi945786/MobHealthIndicators/assets/169622824/27580df8-e5b1-4190-8237-27088a4419f8)

**Comment by vi945786** [comment]
client? server? other mods?

**Comment by dotGrim** [comment]
1.20.4, Fabric 0.15.10-1.20.4
Server's vanilla, but I've seen it happen on both vanilla & paper servers

Full Mod List:

MobHealthIndicator 1.20.4 1.2.1
Nvidium 0.2.6 beta
Sodium 1.20.4 0.5.8
Iris 1.20.4 1.7.0
LazyDFU 0.1.3

Fabric API 1.20.4 0.97.0
Fabric Language Kotlin 1.10.19+kotlin.1.9.23
Cloth Config 13.0.121

Appleskin 1.20.3 2.5.1
BetterPingDisplay 1.20.4 1.1.1
Capes 1.20.2 1.5.3
Eating Animation 1.20+ 1.9.61
Emoji Type 1.20.4 2.2.3
Enhanced Attack Indicator 1.20.3 1.0.4
Entity Model Features 1.20.4 2.0.2
Entity Texture Features 1.20.4 6.0.1
Essential 1.20.4 1-3-1-3
Falling Leaves 1.20.1 1.15.6
Fast IP Ping 1.20.4 1.0.1
Gamma Shifter 1.20.4 1.0.4
ModMenu 9.2.0
MoreChatHistory 1.3.0
MouseTweaks 1.20 2.26
nbttooltips 1.20.x 0.1.4
Perspektive 1.3.4
Status Effect Bars 1.0.4
Xaero's Minimap & Worldmap 24.1.1 & 1.38.4

**Comment by vi945786** [comment]
the problem seems to be using iris with dynamic brightness

**Comment by vi945786** [comment]
https://modrinth.com/mod/mobhealthindicators/version/1.2.2
