### ISSUE TITLE
1.2.2 on 1.20.4 crashes on startup

### ISSUE THREAD

**Issue by dotGrim** [vi945786/MobHealthIndicators#6]
![image](https://github.com/vi945786/MobHealthIndicators/assets/169622824/400cb2a9-4e96-4f71-ab95-21f3af4faa43)

Using the same modlist, fabric version and game version as my previous post; only difference is mod version 1.2.1 -> 1.2.2

--------------------------

1.20.4, Fabric 0.15.10-1.20.4

MobHealthIndicator 1.20.4 1.2.2
Nvidium 0.2.6 beta
Sodium 1.20.4 0.5.8
Iris 1.20.4 1.7.0
LazyDFU 0.1.3

Fabric API 1.20.4 0.97.0
Fabric Language Kotlin 1.10.19+kotlin.1.9.23
Cloth Config 13.0.121

Appleskin 1.20.3 2.5.1
BetterPingDisplay 1.20.4 1.1.1
Capes 1.20.2 1.5.3
Eating Animation 1.20+ 1.9.61
Emoji Type 1.20.4 2.2.3
Enhanced Attack Indicator 1.20.3 1.0.4
Entity Model Features 1.20.4 2.0.2
Entity Texture Features 1.20.4 6.0.1
Essential 1.20.4 1-3-1-3
Falling Leaves 1.20.1 1.15.6
Fast IP Ping 1.20.4 1.0.1
Gamma Shifter 1.20.4 1.0.4
ModMenu 9.2.0
MoreChatHistory 1.3.0
MouseTweaks 1.20 2.26
nbttooltips 1.20.x 0.1.4
Perspektive 1.3.4
Status Effect Bars 1.0.4
Xaero's Minimap & Worldmap 24.1.1 & 1.38.4

**Comment by vi945786** [comment]
https://modrinth.com/mod/mob-health-indicators/version/1.3
