### ISSUE TITLE
Revert the settings menu and texture pack support.

### ISSUE THREAD

**Issue by Ethanwu0608** [vi945786/MobHealthIndicators#7]
The newest version (v1.3) is not showing my own texture pack heart,

**Comment by Ethanwu0608** [comment]
pls bring back the settings menu

**Comment by vi945786** [comment]
Texture packs work for me on all 3 versions the mod supports so I'm gonna need more information,
and I replaced the config screen with commands.

**Comment by vi945786** [comment]
couldn't reproduce the issue
