### ISSUE TITLE
Texture pack hearts not showing in the newest version

### ISSUE THREAD

**Issue by Ethanwu0608** [vi945786/MobHealthIndicators#8]
new: (v1.3.1)
![image](https://github.com/user-attachments/assets/fc546b68-4ee6-4446-8233-96ce1179ffef)

old: (v1.2.2)
![image](https://github.com/user-attachments/assets/973791ed-db1d-466a-90b2-236a4ca90e15)

**Comment by vi945786** [comment]
can I get the download link?

**Comment by Ethanwu0608** [comment]
> can I get the download link?

https://modrinth.com/mod/mob-health-indicators/changelog

[mobhealthindicators.zip](https://github.com/user-attachments/files/16229373/mobhealthindicators.zip)

**Comment by vi945786** [comment]
i meant the download link of the texture pack

**Comment by Ethanwu0608** [comment]
> i meant the download link of the texture pack

https://faithfulpack.net/classicfaithful/32x-programmer-art

**Comment by Ethanwu0608** [comment]
> i meant the download link of the texture pack

Thanks, the issue has been resolved.
